"""add transcript_reviewed_at to post

Revision ID: 4ac003b07c70
Revises: e5502cd9c548
Create Date: 2026-08-28 12:12:55.214784

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4ac003b07c70'
down_revision = 'e5502cd9c548'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transcript_reviewed_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('post', schema=None) as batch_op:
        batch_op.drop_column('transcript_reviewed_at')

    # ### end Alembic commands ###
