"""add feed_title_prefix to app_settings

Revision ID: 6c491b61edf2
Revises: b69cc952e445
Create Date: 2026-08-11 13:23:04.271704

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "6c491b61edf2"
down_revision = "b69cc952e445"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "feed_title_prefix",
                sa.String(length=128),
                nullable=False,
                server_default="[podly]",  # ensure existing SQLite rows get a value
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("app_settings", schema=None) as batch_op:
        batch_op.drop_column("feed_title_prefix")

    # ### end Alembic commands ###
