"""add ad corrections

Revision ID: 8a53af8667d7
Revises: 24d4825ac378
Create Date: 2026-08-17 12:58:55.923509

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "8a53af8667d7"
down_revision = "24d4825ac378"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "ad_correction",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("feed_id", sa.Integer(), nullable=False),
        sa.Column("created_by_user_id", sa.Integer(), nullable=True),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("label", sa.String(length=16), nullable=False),
        sa.Column("start_time", sa.Float(), nullable=False),
        sa.Column("end_time", sa.Float(), nullable=False),
        sa.Column("segment_ids", sa.JSON(), nullable=True),
        sa.Column("source_identification_ids", sa.JSON(), nullable=True),
        sa.Column("reason", sa.Text(), nullable=True),
        sa.Column("example_text", sa.Text(), nullable=True),
        sa.Column("transcript_model_call_id", sa.Integer(), nullable=True),
        sa.Column("stale", sa.Boolean(), nullable=False),
        sa.Column("supersedes_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["created_by_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["feed_id"],
            ["feed.id"],
        ),
        sa.ForeignKeyConstraint(
            ["post_id"],
            ["post.id"],
        ),
        sa.ForeignKeyConstraint(
            ["supersedes_id"],
            ["ad_correction.id"],
        ),
        sa.ForeignKeyConstraint(
            ["transcript_model_call_id"],
            ["model_call.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("ad_correction", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_ad_correction_feed_id"), ["feed_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ad_correction_post_id"), ["post_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_ad_correction_stale"), ["stale"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("ad_correction", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_ad_correction_stale"))
        batch_op.drop_index(batch_op.f("ix_ad_correction_post_id"))
        batch_op.drop_index(batch_op.f("ix_ad_correction_feed_id"))

    op.drop_table("ad_correction")
    # ### end Alembic commands ###
