"""add custom_llm_ad_prompt to feed

Revision ID: a9f8e7d6c5b4
Revises: 3e5eebc6b3b1
Create Date: 2026-06-08 16:00:00.000000

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a9f8e7d6c5b4"
down_revision = "3e5eebc6b3b1"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "custom_llm_ad_prompt",
                sa.Text(),
                nullable=True,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("custom_llm_ad_prompt")

    # ### end Alembic commands ###
