"""add last_fetched_at to feed

Revision ID: e2cc4c50e355
Revises: 48fd92cd848d
Create Date: 2026-08-07 09:47:04.409954

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e2cc4c50e355"
down_revision = "48fd92cd848d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.add_column(sa.Column("last_fetched_at", sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("feed", schema=None) as batch_op:
        batch_op.drop_column("last_fetched_at")

    # ### end Alembic commands ###
